version: '3.9'
services:
  database:
    image: mysql:8.0.28
    container_name: ably_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ably
      - MYSQL_USER=ably
      - MYSQL_PASSWORD=ably
    volumes:
      - "./docker/mysql/mysql-init-files/:/docker-entrypoint-initdb.d/"
      - "./docker/mysql/mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - ably
  redis:
    image: redis:6.2
    container_name: ably_redis
    ports:
      - "6379:6379"
    command: redis-server --port 6379
    networks:
      - ably
networks:
  ably:
    name: ablyNetwork
    driver: bridge
